corepart-$(CONFIG_KERRIGHED) += tools arch/$(ARCH)

corepart-$(CONFIG_KRG_COMMUNICATION_FRAMEWORK) += rpc
corepart-$(CONFIG_KRG_CAP) += capability
corepart-$(CONFIG_KRG_CTNR) += ctnr
corepart-$(CONFIG_KRG_MM) += mm
corepart-$(CONFIG_KRG_IPC) += ipc
corepart-$(CONFIG_KRG_DVFS) += fs
corepart-$(CONFIG_KRG_FAF) += fs/faf
corepart-$(CONFIG_KRG_PROCFS) += procfs
corepart-$(CONFIG_KRG_PROC) += proc
corepart-$(CONFIG_KRG_SCHED_CONFIG) += scheduler/core
corepart-$(CONFIG_KRG_SCHED_LEGACY) += scheduler_old
corepart-$(CONFIG_KRG_HOTPLUG) += hotplug
corepart-$(CONFIG_KRG_EPM) += epm ghost epm/application

corepart += $(corepart-y)

corename += $(foreach n,$(corepart),$(shell basename $(n)))
objname = $(patsubst %, %/, $(corepart))

obj-m += $(objname)

EXTRA_CFLAGS += -I$(M) -Wall -Werror
KRG_BUILD_PATH := $(M)
