if BUILD_LIBS
LIBKERRIGHED = libkerrighed
LIBKRGTHREAD = libkrgthread

CLEANFILES := libkerrighed* libkrgthread*

#EF# hack for avoiding the usage of an old /usr/lib/libkerrighed.so
libkerrighed: libkerrighed.la libkerrighed_uptodate

libkerrighed_uptodate:
	if ! $(MAKE) --question -C $(top_builddir)/../libs/libkerrighed > /dev/null 2>&1 ; then \
	  rm -f libkerrighed*; \
	  $(MAKE) libkerrighed.la; \
	fi

libkerrighed.la:
	$(MAKE) -C $(top_builddir)/../libs/libkerrighed install-libLTLIBRARIES libdir=$(PWD) DESTDIR="" && \
	sed -e 's,^libdir=.*$$,libdir=$$(pwd),' < libkerrighed.la > libkerrighed.la_mod && \
	mv libkerrighed.la_mod libkerrighed.la
	touch libkerrighed
endif
