obj-m += $(mods-y)

mods-$(CONFIG_KRG_SCHED_CONFIG_THRESHOLD_FILTER) += threshold_filter.o
mods-$(CONFIG_KRG_SCHED_CONFIG_FREQ_LIMIT_FILTER) += freq_limit_filter.o
mods-$(CONFIG_KRG_SCHED_CONFIG_REMOTE_CACHE_FILTER) += remote_cache_filter.o

EXTRA_CFLAGS += -I$(M)/../.. -Wall -Werror
