#!/bin/sh

set -e

IP=/bin/ip
PID=$1

session_id=$(cat /sys/kerrighed/session_id)
node_id=$(cat /sys/kerrighed/node_id)

mac=f0:00:00:00:$(printf %02x $session_id):$(printf %02x $node_id)
vlanid=$session_id

$IP link add link eth0 address $mac krg0 type vlan id $vlanid
$IP link set krg0 mtu 1400
$IP link set krg0 netns $PID

echo krg0 $mac $vlanid > /var/run/kerrighed/net-conf
