#!/bin/bash
#
# update-rc.d Register kerrighed service
#
# Author:	Jean Parpaillon <jean.parpaillon@kerlabs.com>
#
# Copyright:    INRIA-IRISA - 2006-2007
#               Kerlabs 2007-2009
#
set -e

PROGRAM=$(basename ${0})
DEBIAN_SCRIPT=/usr/sbin/update-rc.d
REDHAT_SCRIPT=/sbin/chkconfig
# Have a look at /etc/rcS.d/README to understand
LEVEL=61

error() {
		echo "E: $@"
}

check_root() {
		if test "$(id -u)" != "0"
		then
				error "Must be run as root"
				exit 0
		fi
}

#
# Register kerrighed service
#
i_install() {
		if [ -e ${DEBIAN_SCRIPT} ]; then
				${CHROOT} ${DEBIAN_SCRIPT} kerrighed defaults ${LEVEL}
		elif [ -e ${REDHAT_SCRIPT} ]; then
				${CHROOT} ${REDHAT_SCRIPT} -add kerrighed
		else
				error "Unknown distribution. Can not install init script."
				exit 1
		fi
}

#
# Remove kerrighed service
#
i_remove() {
		if [ -e ${DEBIAN_SCRIPT} ]; then
				${CHROOT} ${DEBIAN_SCRIPT} -f kerrighed remove
		elif [ -e ${REDHAT_SCRIPT} ]; then
				${CHROOT} ${REDHAT_SCRIPT} -del kerrighed
		else
				error "Unknown distribution. Can not remove init script."
				exit 1
		fi
}

#
# Check if distribution is supported
#
i_check() {
		if [ -e ${DEBIAN_SCRIPT} ]; then
				return 0
		elif [ -e ${REDHAT_SCRIPT} ]; then
				return 0
		else
				return 1
		fi
}

ARGUMENTS="$(getopt --longoptions install,remove,chroot:,check --name=${PROGRAM} --options irc:s --shell sh -- "${@}")"
if [ "${?}" != "0" ]
then
    error "Error parsing options"
    exit 1
fi

eval set -- "${ARGUMENTS}"

while true
do
    case "${1}" in
	--install|-i)
	    action=install
	    shift
	    ;;
	--remove|-r)
	    action=remove
	    shift
	    ;;
	--chroot|-c)
	    CHROOT="chroot ${2}"
	    shift 2
	    ;;
	--check|-s)
			action=check
			shift
			;;
	--)
	    shift
	    break
	    ;;
	*)
	    error "Error parsing options"
	    exit 1
	    ;;
    esac
done

if test "${action}" = "install"; then
		check_root
    i_install
		ret=$?
elif test "${action}" = "remove"; then
		check_root
    i_remove
		ret=$?
elif test "${action}" = "check"; then
		i_check
		ret=$?
else
		error "Unknown action: $action"
		ret=1
fi

exit $ret
