obj-m += krgbuiltin.o

krgbuiltin-objs := mobility.o fs.o regular_file_mgr.o file_struct_io_linker.o \
		   physical_fs.o file.o

krgbuiltin-$(CONFIG_KRG_STREAM) := 

krgbuiltin-$(CONFIG_KRG_EPM) := mobility.o
krgbuiltin-$(CONFIG_KRG_DEBUG) := debug_fs.o 

krgbuiltin-objs += $(krgbuiltin-y)

EXTRA_CFLAGS += -I$(M) -Wall -Werror
