#!/bin/bash
###############################################################################
##
## Copyright (c) INRIA, 2007
##
## This program is free software;  you can redistribute it and#or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program;  if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
###############################################################################
#
# Description:  Test program for Kerrighed checkpoint/restart of single
#               process. This test is mainly usefull to check the cancellation
#               of pid reservation
#
# Author:       Matthieu Fertré, matthieu.fertre@irisa.fr
#

source `dirname $0`/lib_cr.sh

description="Restart after a first failure: Run, C, K, mv some files, R (FAIL), R"

cr_abort02()
{
    TCID="$FUNCNAME"               # Identifier of this testcase.
    TST_COUNT=$[$TST_COUNT+1]      # Test case number.


    local workdir=`mktemp -d`
    mkdir $workdir/tmp/

    cp `which $TESTCMD` $workdir/
    cp `which $TESTCMD` $workdir/tmp/

    local OLDPATH=$PATH

    export PATH="$workdir/:$OLDPATH"

    runcommand +CHECKPOINTABLE || return $?

    export PATH=$OLDPATH

    checkpoint_process $PID $TESTCMD || return $?

    kill_group $PID $TESTCMD || return $?

    rm -rf $workdir/$TESTCMD

    restart_process_must_fail $PID 1 $TESTCMD || return $?

    touch $workdir/$TESTCMD

    restart_process_must_fail $PID 1 $TESTCMD || return $?

    cp -f $workdir/tmp/$TESTCMD $workdir/

    restart_process $PID 1 $TESTCMD || return $?

    kill_group $PID $TESTCMD || return $?

    local r=$?

    print_success $r

    rm -rf $workdir > /dev/null 2>&1

    return $r
}

CR_setup $@ || exit $?

cr_abort02
