#!/bin/bash
###############################################################################
##
## Copyright (c) INRIA, 2007
##
## This program is free software;  you can redistribute it and#or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program;  if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
###############################################################################
#
# Description:  Test program for Kerrighed checkpoint/restart with blender.
#               This test is basically a copy of cr10
#
# Author:       Matthieu Fertré, matthieu.fertre@kerlabs.com
#

source `dirname $0`/lib_cr.sh

description="Run, C, K, R, C, K, R, R (EBUSY), K, R - Blender"

TESTCMD="blender-bin"
inputbl="`dirname $0`/duck11_peaking.blend"
outputchecked="`dirname $0`/duck11_peaking_render_1.png"

# Run, C, K, R, C, K, R, R (EBUSY), K, R
cr_blender()
{
    TCID="$FUNCNAME"               # Identifier of this testcase.
    TST_COUNT=$[$TST_COUNT+1]      # Test case number.

    # look for Blender
    which $TESTCMD > /dev/null
    if [ $? -ne 0 ]; then
	tst_resm TWARN "Can not run this test if $TESTCMD is not installed"
	return 0 # to not stop krgltp
    fi

    if [ ! -f $inputbl ]; then
	tst_resm TWARN "Can not run this test if $inputbl is not installed"
	return 0 # to not stop krgltp
    fi

    if [ ! -f $outputchecked ]; then
	tst_resm TWARN "Can not run this test if $outputchecked is not installed"
	return 0 # to not stop krgltp
    fi

    local output="$CHKPTDIR/render_krg_$$_#"
    local renderoptions="-F PNG -f 1"

    TESTCMD_OPTIONS="-b $inputbl -o $output $renderoptions"
    runcommand +CHECKPOINTABLE 1 nosync || return $?

    # let the process really begin
    sleep 20

    checkpoint_process $PID $TESTCMD || return $?

    kill_group $PID $TESTCMD || return $?

    restart_process $PID 1 $TESTCMD || return $?

    checkpoint_process $PID $TESTCMD || return $?

    kill_group $PID $TESTCMD || return $?

    restart_process $PID 2 $TESTCMD || return $?

    restart_process_must_fail $PID 1 $TESTCMD || return $?

    kill_group $PID $TESTCMD || return $?

    restart_foreground_process $PID 2 $TESTCMD || return $?

    # check image are the same
    diff -q $outputchecked $CHKPTDIR/render_krg_$$_1.png || return $?

    print_success $?
    return $?
}

CR_setup $@ || exit $?

cr_blender || exit $?
