#!/bin/bash
###############################################################################
##
## Copyright (c) INRIA, 2007
##
## This program is free software;  you can redistribute it and#or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program;  if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
###############################################################################
#
# Description:  Test program for Kerrighed checkpoint/restart of a application
#               with 2 processes. A signal is sent to all the processes at the
#               end of the checkpoint.
#
# Author:       Matthieu Fertré, matthieu.fertre@irisa.fr
#

source `dirname $0`/lib_cr.sh

description="(2processes) C/R test: Run, C (+SIGTERM), R"

# Application with 2 processes
TESTCMD="bi-double"
TESTCMD_OPTIONS="-q"
SIGTERM=15

# C/R test of Application (2 processes),
# sending signal at the end of checkpoint: Run, C, R
cr-signal01()
{
    TCID="$FUNCNAME"               # Identifier of this testcase.
    TST_COUNT=$[$TST_COUNT+1]      # Test case number.

    runcommand +CHECKPOINTABLE 2 || return $?

    checkpoint_process_w_signal $PID $TESTCMD $SIGTERM || return $?

    check_group_not_exists_in_ps $PID $TESTCMD || return $?

    restart_process $PID 1 $TESTCMD || return $?

    kill_group $PID $TESTCMD || return $?

    print_success $?
    return $?
}

CR_setup $@ || exit $?

cr-signal01 || exit $?
