#!/bin/sh

# Round robin balancing with remote clone
SCHEDULER_PATH=/config/krg_scheduler/schedulers/rr

mkdir -p "$SCHEDULER_PATH/round_robin_balancer" && \
echo 1 > "$SCHEDULER_PATH/process_set/handle_all"


# Dynamic Memory use balancing with migration
SCHEDULER_NAME=memory_balanced
# Do not try to migrate if more than 300MB of local memory is free
MEMORY_THRESHOLD=$(( 300 * 1024 ))
# 2 seconds between each migration
MIGRATION_INTERVAL=2000000000
# Refresh remote node loads every second
POLL_INTERVAL=1000

SCHEDULER_PATH="schedulers/$SCHEDULER_NAME"
POLICY_PATH="$SCHEDULER_PATH/mosix_load_balancer"
MEM_PROBE_PATH=probes/mem_probe
MIGRATION_PROBE_PATH=probes/migration_probe
LOCAL_DIFF_PATH="$POLICY_PATH/local_load/diff_filter"
LOCAL_CONSTANT_PATH="$LOCAL_DIFF_PATH/constant_filter"
FREQ_LIMIT_PATH="$LOCAL_DIFF_PATH/second_value/freq_limit_filter"
THRESHOLD_PATH="$FREQ_LIMIT_PATH/low_threshold_filter"
REMOTE_DIFF_PATH="$POLICY_PATH/remote_load/diff_filter"
REMOTE_LOAD_CACHE_PATH="$REMOTE_DIFF_PATH/second_value/remote_cache_filter"
REMOTE_CONSTANT_PATH="$REMOTE_DIFF_PATH/constant_filter"

total_mem=$(sed -n 's/^MemTotal:[^0-9]*\([0-9]*\) kB$/\1/p' < /proc/meminfo)

cd /config/krg_scheduler && \
mkdir "$MEM_PROBE_PATH" && \
mkdir "$MIGRATION_PROBE_PATH" && \
mkdir -p "$THRESHOLD_PATH" && \
echo $MIGRATION_INTERVAL > "$FREQ_LIMIT_PATH/min_interval" && \
echo $MEMORY_THRESHOLD > "$THRESHOLD_PATH/threshold" && \
mkdir "$LOCAL_CONSTANT_PATH" && \
echo $total_mem > "$LOCAL_CONSTANT_PATH/constant" && \
mkdir -p "$REMOTE_LOAD_CACHE_PATH" && \
echo $POLL_INTERVAL > "$REMOTE_LOAD_CACHE_PATH/polling_period" && \
mkdir "$REMOTE_CONSTANT_PATH" && \
echo $total_mem > "$REMOTE_CONSTANT_PATH/constant" && \
ln -s "$MIGRATION_PROBE_PATH/last_migration" "$FREQ_LIMIT_PATH/last_event/migration" && \
ln -s "$MEM_PROBE_PATH/task_rss" "$POLICY_PATH/process_load/task_rss" && \
ln -s "$MEM_PROBE_PATH/ram_free" "$REMOTE_LOAD_CACHE_PATH/free_mem" && \
ln -s "$MEM_PROBE_PATH/ram_free" "$THRESHOLD_PATH/free_mem" && \
echo 1 > "$SCHEDULER_PATH/process_set/handle_all"
