#!/bin/sh
# Script to enable/disable pritting of error messages related
# to Kerrighed.

print_usage() {
    echo $0 "+epm|-epm|+faf|-faf"
}

dbgdir=`mktemp -d`
mount -t debugfs debugfs $dbgdir
if [ $? -ne 0 ]; then
    echo "Fail to mount debugfs"
    exit 1
fi

control=$dbgdir/dynamic_debug/control
if [ ! -e $control ]; then
    echo "Kernel has been compiled without CONFIG_DYNAMIC_DEBUG"
    exit 1
fi

case "$1" in
    "+epm")
	echo 'file epm.c +p' > $control;;
    "-epm")
	echo 'file epm.c -p' > $control;;
    "+faf")
	echo 'file faf.c +p' > $control;;
    "-faf")
	echo 'file faf.c -p' > $control;;
    *)
	print_usage
	exit 1;;
esac

umount $dbgdir
