obj-m += $(mods-y)

mods-$(CONFIG_KRG_SCHED_CONFIG_ECHO_POLICY) += echo_policy.o

mods-$(CONFIG_KRG_SCHED_CONFIG_MOSIX_LOAD_BALANCER) += mosix_load_balancer.o
mods-$(CONFIG_KRG_SCHED_CONFIG_ROUND_ROBIN_BALANCER) += round_robin_balancer.o

EXTRA_CFLAGS += -I$(M)/../.. -Wall -Werror
