obj-m += krgbuiltin.o

krgbuiltin-objs := epm.o ghost_process_management.o \
	migration.o checkpoint.o ghost_process_api.o \
	migration_api.o procfs.o restart.o g_signal.o \
	krg_ptrace.o action.o epm_hotplug.o

krgbuiltin-$(CONFIG_KRG_FD) += fork_delay.o

EXTRA_CFLAGS += -I$(M) -Wall -Werror

