#!/bin/bash
#
# update-rc.d Register kerrighed service for Debian-like distros
#
# Author:	Jean Parpaillon <jean.parpaillon@kerlabs.com>
#
# Copyright:    INRIA-IRISA - 2006-2007
#               Kerlabs 2007-2009
#
set -e

PROGRAM=$(basename ${0})
SCRIPT=/usr/sbin/update-rc.d
# Have a look at /etc/rcS.d/README to understand
LEVEL=61

#
# Register kerrighed service
#
i_install() {
    ${CHROOT} ${SCRIPT} kerrighed defaults ${LEVEL}
}

#
# Remove kerrighed service
#
i_remove() {
    ${CHROOT} ${SCRIPT} -f kerrighed remove
}

if test "$(id -u)" != "0"
then
    echo "Must be run as root"
    exit 1
fi

ARGUMENTS="$(getopt --longoptions install,remove,chroot: --name=${PROGRAM} --options irc: --shell sh -- "${@}")"
if [ "${?}" != "0" ]
then
    Error "Error parsing options"
    exit 1
fi

eval set -- "${ARGUMENTS}"

CHROOT_DIR=
while true
do
    case "${1}" in
	--install|-i)
	    action=install
	    shift
	    ;;
	--remove|-r)
	    action=remove
	    shift
	    ;;
	--chroot|-c)
	    CHROOT_DIR="${2}"
	    CHROOT="chroot ${CHROOT_DIR}"
	    shift 2
	    ;;
	--)
	    shift
	    break
	    ;;
	*)
	    Error "Error parsing options"
	    exit 1
	    ;;
    esac
done

if test ! -x ${CHROOT_DIR}${SCRIPT}; then
    echo "Missing ${CHROOT_DIR}${SCRIPT}, aborting..."
    exit 0
fi

if test "${action}" = "install"; then
    i_install
elif test "${action}" = "remove"; then
    i_remove
fi

exit 0
