#!/bin/bash
#
# update-rc.d Register kerrighed service for RedHat-like distros
#
# Copyright 2006-2007 INRIA, All rights reserved
# Copyright 2009 Kerlabs, All rights reserved
#
# Author:
#   Jean Parpaillon <jean.parpaillon@kerlabs.com>
#

SCRIPT=/sbin/chkconfig

#
# Register kerrighed service
#
function i_install() {
    $CHROOT $SCRIPT -add kerrighed
}

#
# Remove kerrighed service
#
function i_remove() {
    $CHROOT $SCRIPT --del kerrighed
}

function failed() {
    echo " fail."
    if test -n "$CHROOT"; then
	echo "Does your chroot system contains '$SCRIPT' ?"
    fi
}

CHROOT_DIR=
while getopts irc: option
do
  case $option in
      c)
	  CHROOT_DIR=$OPTARG
	  CHROOT=/usr/sbin/chroot $CHROOT_DIR
	  ;;
      i)
	  action=install
	  ;;
      r)
	  action=remove
	  ;;
  esac
done

if test ! -x ${CHROOT_DIR}${SCRIPT}; then
    echo "Missing ${CHROOT_DIR}${SCRIPT}, aborting..."
    exit 0
fi

if test "$action" = "install"; then
    echo -n "Register kerrighed service"
    i_install || failed
    echo "."
elif test "$action" = "remove"; then
    echo -n "Remove kerrighed service"
    i_remove || failed
    echo "."
fi
    
exit 0
