#!/bin/bash
#
# update-rc.d Register kerrighed service for RedHat-like distros
#
# Author:	Jean Parpaillon <jean.parpaillon@irisa.fr>
#               PARIS Research Team - IRISA
#
# Copyright:    INRIA-IRISA - 2006-2007
#

SCRIPT=/sbin/chkconfig

#
# Register kerrighed service
#
function i_install() {
    $CHROOT $SCRIPT -add kerrighed
}

#
# Remove kerrighed service
#
function i_remove() {
    $CHROOT $SCRIPT --del kerrighed
}

function failed() {
    echo " fail."
    if test -n "$CHROOT"; then
	echo "Does your chroot system contains '$SCRIPT' ?"
    fi
}

while getopts irc: option
do
  case $option in 
      c)
	  CHROOT=/usr/sbin/chroot $OPTARG
	  ;;
      i)
	  action=install
	  ;;
      r)
	  action=remove
	  ;;
  esac
done

if test "$action" = "install"; then
    echo -n "Register kerrighed service"
    i_install || failed
    echo "."
elif test "$action" = "remove"; then
    echo -n "Remove kerrighed service"
    i_remove || failed
    echo "."
fi
    
exit 0
