#!/bin/sh

set -e

IPTABLES=/sbin/iptables
IP=/bin/ip

session_id=$(cat /sys/kerrighed/session_id)
node_id=$(cat /sys/kerrighed/node_id)

IFNAME=krg0
ADDR=10.4.$(( 192 + $session_id )).1
PREFIX=$ADDR/18
MAC=01:00:00:00:$(printf %02x $(( 128 + $session_id ))):00

NR_NODES=4

$IPTABLES -I INPUT -i $IFNAME -d $ADDR -j CLUSTERIP --new --total-nodes $NR_NODES --local-node $node_id --hashmode sourceip --clustermac $MAC
$IP addr add $PREFIX dev $IFNAME
